name: Generate Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: ulisesdm
          outputs: dist/snake.svg

      - name: Commit snake file
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add dist/snake.svg

          git commit -m "generate snake" || echo "no changes"

          git push
