name: Generate Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: UlisesDM
          outputs: dist/snake.svg

      - name: Commit snake file
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add dist/snake.svg
          git commit -m "generate snake" || echo "no changes"
          git push
